title: Programación desde cero
description: Un blog con material que escribo para mis cursos de programación y otras cosillas que se me ocurren. No English version is available because these are mostly teaching materials that I create for my students.
author: Patricia E. Miguel
logo: /blog/static/img/avatar.png
github: https://github.com/patr1c1a
about: Artículos introductorios de programación y otras yerbas

baseurl: "https://patr1c1a.github.io"
url: "https://patr1c1a.github.io"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
