title: Programación desde cero
description: Recursos educativos sobre programación y temas relacionados.
author: Patricia E. Miguel
logo: /static/img/avatar.png
github: https://github.com/programacion-desde-cero
about: Recursos educativos sobre programación y temas relacionados.

baseurl: "http://patriciaemiguel.com"
url: "http://patriciaemiguel.com"

allowsearch: true

disqus_shortname: patr1c1a
google_analytics: UA-76752123-1

share:
  twitter_username: Programacion_0
  fb_appid: 000000000000

social-network-links:
  youtube: c/ProgramacionDesdeCero
  facebook: ProgramacionDesdeCeroParaTodos
  twitter: Programacion_0
  instagram: programaciondesdecero
  github: programacion-desde-cero
  rss: true

share-links-active:
  twitter: true
  facebook: true
  youtube: true
  instagram: true
  github: true
  rss: true
  
link-tags: true  
  
enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
