title: Programación desde cero
description: Material que escribo para mis cursos de programación y otras cosillas que se me ocurren. No English version is available because these are mostly teaching materials that I create for my students.
author: Patricia E. Miguel
logo: /static/img/avatar.png
github: https://github.com/patr1c1a
about: Artículos introductorios a la programación. [No English version, as these are mostly teaching resources].
#Artículos introductorios de programación y otras yerbas

baseurl: "http://patriciaemiguel.com/"
url: "http://patriciaemiguel.com/"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
